### ISSUE TITLE
Nome do trabalho

### ISSUE THREAD

**Issue by darmsDD** [projeto-de-algoritmos/Grafos1_Top#13]
## Descrição
O nome do projeto é CineGraph mas o nome que ficou para o trabalho está como Grafos1_Top, o padrão observado foi que o nome do trabalho deveria ser Grafos1_NomedoProjeto, resultando em Grafos1_CineGraph.

**Comment by ErickGiffoni** [comment]
Thanks for the feedback. Although this really wasn't a "problem" we appreciate your words !
Solved.
